In [ ]:
import numpy as np

games = np.load('gamesCoups.npy')
labels = np.load('rawLabels.npy')

In [ ]:
# scripts de conversion des parties notées en Long Algebraic Form en véritable tableau de jeu

def createBoard():
    plateau = np.zeros([8,8])

    # On ajoute les pions (valeur : 1)

    for j in range (0,8):
        plateau[1][j] = -1
        plateau[6][j] = 1

    # On ajoute les tours (valeur : 4)

    plateau[7][0] = 5
    plateau[0][0] = -5
    plateau[0][7] = -5
    plateau[7][7] = 5

    # On ajoute les cavaliers (valeur : 2)

    plateau[7][1] = 3
    plateau[0][6] = -3
    plateau[0][1] = -3
    plateau[7][6] = 3

    # On ajoute les fous (valeur : 3)

    plateau[7][2] = 3.5
    plateau[0][2] = -3.5
    plateau[7][5] = 3.5
    plateau[0][5] = -3.5

    # On ajoute les reines (valeur : 5)

    plateau[7][3] = 9
    plateau[0][3] = -9

    # On ajoute les rois (valeur : 6)

    plateau[7][4] = 0
    plateau[0][4] = -0

    return plateau

def string_converter(a):
    if (a=='a'):
        res=0
    if (a=='b'):
        res=1
    if (a=='c'):
        res=2
    if (a=='d'):
        res=3
    if (a=='e'):
        res=4
    if (a=='f'):
        res=5
    if (a=='g'):
        res=6
    if (a=='h'):
        res=7
    return res

def converter(str):
    a=string_converter(str[0])
    b=8-int(str[1])
    c=string_converter(str[2])
    d=8-int(str[3])
    return (b,a,d,c)

def move(str,plateau):
    if (str=='e1g1'):
        plateau[7][6]=plateau[7][4]
        plateau[7][4]=0
        plateau[7][5]=plateau[7][7]
        plateau[7][7]=0
    if (str=='e1c1'):
        plateau[7][2]=plateau[7][4]
        plateau[7][4]=0
        plateau[7][3]=plateau[7][0]
        plateau[7][0]=0
    if (str=='e8g8'):
        plateau[0][6]=plateau[0][4]
        plateau[0][4]=0
        plateau[0][5]=plateau[0][7]
        plateau[0][7]=0
    if (str=='e8c8'):
        plateau[0][2]=plateau[0][4]
        plateau[0][4]=0
        plateau[0][3]=plateau[0][0]
        plateau[0][0]=0
    a,b,c,d=converter(str)
    plateau[c][d]=plateau[a][b]
    plateau[a][b] = 0

In [ ]:
# Remplacement des notations algébriques par des véritables plateaux de jeu

gamesData = []
for game in games:
    plateau = createBoard()
    for pos in game:
        tabPos = []
        move(pos, plateau)
        for x in plateau:
            for y in x:
                tabPos.append(y)
        gamesData.append(tabPos)


                
                
                
                

In [4]:
# on enlève tous les labels évalués à 0

cleanedLabels = []
movesIndex = []
for p in range(0,len(labels)):
    if labels[p] != 0:
        cleanedLabels.append(labels[p])
    if labels[p] == 0:
        movesIndex.append(p)
    

In [5]:
npArrayLabels = np.asarray(cleanedLabels)
np.save('cleanedLabels.npy', npArrayLabels)

In [ ]:
# on enlève tous les coups évalués à 0

cleanedGamesData = []
for r in range(0,len(gamesData)):
    if not(r in movesIndex):
        cleanedGamesData.append(gamesData[r])

In [35]:
print(len(cleanedGamesData) == len(cleanedLabels))

True


In [36]:
npArray = np.asarray(cleanedGamesData)
np.save('newGamesData.npy', npArray)

In [7]:
print(npArrayLabels[0:10])

[ 0.57 -0.02 -0.05  0.01 -0.01 -0.03  0.15  0.05  0.19 -0.02]


In [9]:
# onehot encoding

oneHotEncoded = []

for x in cleanedLabels:
    encoded = [0, 0, 0, 0, 0, 0]
    if x <= -1.5:
        encoded[0] = 1
    if x > -1.5 and x <= -0.5:
        encoded[1] = 1
    if x > -0.5 and x <= 0:
        encoded[2] = 1
    if x > 0 and x <= 0.5:
        encoded[3] = 1
    if x > 0.5 and x <= 1.5:
        encoded[4] = 1
    if x > 1.5:
        encoded[5] = 1
    oneHotEncoded.append(encoded)
        

In [10]:
print(oneHotEncoded[0:10])

[[0, 0, 0, 0, 1, 0], [0, 0, 1, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 1, 0, 0, 0]]


In [11]:
npArrayOneHot = np.asarray(oneHotEncoded)
np.save('newOneHotEncoded.npy', npArrayOneHot)

In [13]:
print(len(oneHotEncoded))

572617


In [11]:
import numpy as np
tab = np.load("newOneHotEncoded.npy")
print(tab[20:23])

[[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]]


In [10]:
import numpy as np
tab = np.load("newGamesData.npy")
print(tab[0:1])

[[-5.   0.  -3.5  0.   0.  -3.5  0.  -5.  -1.   0.   0.  -3.   0.  -1.  -1.
  -1.   0.   0.  -1.   0.  -1.  -3.   0.   0.  -9.  -1.   0.   0.   0.   0.
   3.5  0.   0.   0.   0.   1.   0.   0.   0.   0.   0.   9.   3.   0.   1.
   3.   0.   0.   1.   1.   0.   0.   0.   1.   1.   1.   5.   0.   0.   0.
   0.   3.5  0.   5. ]]
